### ISSUE TITLE
Show how many 'free' views a user has left.

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-limit-post-views#11]
A few requests have come in to show how many free views a user has left.

**Comment by kimcoleman** [comment]
Where would they like this to be displayed? We do have this recipe on the blog to show as a notification "bar" - https://www.paidmembershipspro.com/improve-the-user-experience-and-increase-signups-when-using-the-limit-post-views-add-on/

**Comment by andrewlimaza** [comment]
Thanks Kim! The user asked to have it shown on a restricted post somewhere. This looks like it can work as a solution, not sure if we should build something like this into LPV core?
