### ISSUE TITLE
How limit views for non-members in some posts and others total restricted?

### ISSUE THREAD

**Issue by venturaEffect** [strangerstudios/pmpro-limit-post-views#12]
Post limit views works only if CPT are restricted by membership level. If all are restricted by membership level how can I set the content that has limit views from other that is only possible for members. (not nonmembers can see it) For example, trips has limit views because is restricted but have set to see it non members ten times a month. Jobs is restricted too and nonmembers should not be able to access. Only members.

**Comment by pbrocks** [comment]
Not sure I understand what you are asking here, but if you want to limit non-members to some posts, sure, use Limit Post Views. For what you want to have total restriction, restrict those post by a category.

**Comment by pbrocks** [comment]
There is a filter that gives access to posts that are normally restricted:

You can see it twice in the code:

`https://github.com/strangerstudios/pmpro-limit-post-views/blob/master/pmpro-limit-post-views.php#L78`

`https://github.com/strangerstudios/pmpro-limit-post-views/blob/master/pmpro-limit-post-views.php#L134`

you should be able to add the one type to this, but keep the other out.

**Comment by venturaEffect** [comment]
And where can I write the posts that they have limit access to the one that
they have no access at all. Only if they are members?

Thank you in advance for the help.

**Comment by ideadude** [comment]
It has a been while, so I'm going to close this issue. But please get in touch with us if you are still having problems. Thanks.
