### ISSUE TITLE
Bug: Limit Post Views settings page link broken in PMPro v2.0

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-limit-post-views#13]
The Memberships > Limit Post Views link directs to "wp-admin/pmpro-limitpostviews" in PMPro version 2.0+

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/limit-post-views-5/

**Comment by ideadude** [comment]
Fixed on dev and going to license server soon.
