### ISSUE TITLE
/wp-admin/pmpro-limitpostviews 404 error

### ISSUE THREAD

**Issue by chrisbush-advocate** [strangerstudios/pmpro-limit-post-views#15]
There seems to be an issue with Paid Memberships Pro – Limit Post Views Add On.

Paid Memberships Pro Version 2.0.4
Paid Memberships Pro – Limit Post Views Add On Version .5
WordPress version 5.0.3
PHP version: 7.0.33

When I select “Limit post views” under the memberships menu, i receive a Page not found error 404

for some reason the following link is not accessable:
http://itservices.pictouadvocate.com/wp-admin/pmpro-limitpostviews

pmpro-limitpostviews:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by ideadude** [comment]
This has been fixed on the latest dev branch and will go out to our license server today. Sorry for the delay.

**Comment by ideadude** [comment]
FWIW, this is a common issue we've been having with some of our add ons after our menu change in PMPro Core 2.0
