### ISSUE TITLE
Handle manually added members

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-limit-post-views#16]
Commenter on the blog mentions that "this plugin doesn't work when manually adding members".

Let's make sure the member's start date is set properly when adding members. Also maybe make it possible to manually change the member's start date.

**Comment by JarrydLong** [comment]
Tested this with: 

Limit Post Views Version .6
Add Member From Admin Version .6

Steps I followed: 

- Created a level, assigned a category for it to protect
- Set a limit to the number of views for each level
- Navigated to 'Add a Member'
- Created my member with no level assigned to them

Redirection occurred as expected after reaching the limit for the number of visits.

**Comment by kimcoleman** [comment]
Closing as can't be recreated.
