### ISSUE TITLE
Enhancement: Additional filters to allow for different criteria to be met. 

### ISSUE THREAD

**Issue by JarrydLong** [strangerstudios/pmpro-limit-post-views#21]
Based on the discussion in these two topics: 
https://www.paidmembershipspro.com/forums/topic/limit-post-per-views-per-uri/
https://www.paidmembershipspro.com/forums/topic/limit-post-per-views-per-category/

It would be nice to be able to hook into a filter around the lines of

``if ( empty( $queried_object ) || empty( $queried_object->post_type ) || ! in_array( $queried_object->post_type, $pmprolpv_post_types, true ) ) {
				return;
			}``

Or even in the `pmpro_lpv_redirect` function to check against additional criteria such as URLs or Categories that can be included/excluded explicitly from the limit.

**Comment by kimcoleman** [comment]
This should be possible now with the hooks pmprolpv_allow_view_js and pmprolpv_deny_view_js
