### ISSUE TITLE
Cookie not being set

### ISSUE THREAD

**Issue by andrepetrini** [strangerstudios/pmpro-limit-post-views#22]
Hi, this plugin is not working on my website. I've being in touch with your support and they are not being able to help either. 
The cookie is not being set at all, but I don't believe it's a permission issue, as the `prmpro_visit`  is being set without a problem.

**Comment by ideadude** [comment]
I'm pretty sure this is resolved. There were some fixes to PMPro core around sessions and breaking varnish cache when appropriate.  It has a been while, so I'm going to close this issue. But please get in touch with us if you are still having problems. Thanks.
