### ISSUE TITLE
Bug: Unlimited Views / Not restricting

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-limit-post-views#28]
I'm still working through all the edge cases for this however, here's what I've been able to do so far:

1. Set LPV for non-members to a number, reach your view limit.
2. With the same browser/session, log in as a user with a membership level that has a 'higher' view limit for membership content that they shouldn't have access to.
3. View the content and refresh constantly, a redirect never happens and access to restricted content.

This may be because the pmpro_lpv_limit cookie is shared in a browser and not per user. This would need a bit of work to resolve.

Setting this to use JavaScript seems to help.

![image](https://user-images.githubusercontent.com/12629136/100592959-7d4ac200-3300-11eb-9c36-5301413e75d4.png)

**Comment by kimcoleman** [comment]
This should be resolved now in the rewrite. Closing - we can reopen if this resurfaces.
