### ISSUE TITLE
Not working with LearnDash.

### ISSUE THREAD

**Issue by mitchellcausey** [strangerstudios/pmpro-limit-post-views#4]
Hey there,

I've been trying this for over a year now and it's not quite working. I'd like each lesson within LearnDash (currently behind a PMPro wall) to be indexed and allow people to view a sample.

Each time I try, it sends the user to the course page for the course that the lesson is a part of, rather than allowing them to see the lesson itself.

Any thoughts?

Best,
Mitch

(cornerstoneinteractive.com for reference)

**Comment by ideadude** [comment]
This issue is over 2 years old. My bad. In that time, we've added a filter to limit other CPTs besides the post CPT: pmprolpv_post_types

So you could use that filter and add the LearnDash CPTs to the list so they also allow a certain number of views.
