### ISSUE TITLE
Blank Settings Gives Unlimited Access

### ISSUE THREAD

**Issue by andrewlimaza** [strangerstudios/pmpro-limit-post-views#43]
Leaving the Limit Post View settings blank (nothing entered) gives unlimited access to content.

Steps to recreate:

1. Install Limit Post Views
2. Ensure the Limit Post Views Settings are blank (nothing entered into these fields)
3. Unlimited access to restricted content.

Similar issue - https://github.com/strangerstudios/pmpro-limit-post-views/issues/28

**Comment by ideadude** [comment]
This should be fixed in the latest version. Fix going out to license server soon.
