### ISSUE TITLE
After installation it gets Parse error: syntax error, unexpected '{' in

### ISSUE THREAD

**Issue by adcadesigns** [strangerstudios/pmpro-limit-post-views#44]
after installing from a fresh wp install, i get this error "Parse error: syntax error, unexpected '{' in E:\XXX\www\membership\wp-content\plugins\pmpro-limit-post-views-dev\adminpages\limitpostviews.php on line 40"

Please note: i already created a plans and members

**Comment by JarrydLong** [comment]
Hi there

Thank you for reaching out to us. 

Please rename the `pmpro-limit-post-views-dev` file to `pmpro-limit-post-views` - this should resolve the issue. 

For any other queries related to this Add On, please feel free to open a support ticket with us over at https://www.paidmembershipspro.com/new-topic/

**Comment by JarrydLong** [comment]
Please note that downloading the add-on from the dev branch can result in unexpected results. Please ensure you pull from the master branch instead.

**Comment by gianght90** [comment]
missing 1 sign ) in line 40 and the following lines.

**Comment by JarrydLong** [comment]
@gianght90 I've tested this on my side however have not been able to replicate this. Please open a new issue and provide steps on how we can replicate this as well as provide a screenshot of the error if possible and what version of Limit Post Views is installed so that we can investigate further?
