### ISSUE TITLE
Syntax error, site stops

### ISSUE THREAD

**Issue by vasudevz** [strangerstudios/pmpro-limit-post-views#47]
When I uploaded the plugin, the plugin displayed an error and I got the following information in my email.

When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.8.1
Current theme: BuddyXChild (version 1.0)
Current plugin: Paid Memberships Pro - Limit Post Views Add On (version .6)
PHP version 7.4.15

Error Details
=============
An error of type E_PARSE was caused in line 40 of the file /home/wp_h6mhb3/indikaari.in/wp-content/plugins/pmpro-limit-post-views-dev/adminpages/limitpostviews.php. Error message: syntax error, unexpected '{'

**Comment by ideadude** [comment]
Fixed in latest dev version. Thanks. Fix being pushed out to the license server soon.
