### ISSUE TITLE
Illegal return statement

### ISSUE THREAD

**Issue by michaelbourne** [strangerstudios/pmpro-limit-post-views#60]
**Describe the bug**
I'm seeing an `Uncaught SyntaxError: Illegal return statement` coming from `pmprolpv.js` line 32: `eval( response.data );`

This seems to be linked to both:
https://github.com/strangerstudios/pmpro-limit-post-views/blob/dev/includes/restriction.php#L53
https://github.com/strangerstudios/pmpro-limit-post-views/blob/dev/includes/restriction.php#L61

**To Reproduce**
I'm testing as a registered user with a free account that has post views limited. This error occurs when I'm redirected to the LPV page, or on some other random pages all the time like the home page.

**Screenshots**
![image](https://github.com/strangerstudios/pmpro-limit-post-views/assets/22846422/a27504d9-13f0-463e-98e8-a049e22063bc)

**Expected behavior**
The JSON sent back to eval should probably be blank?

**WordPress Environment**
<details>
```
LPV 1.0
```
</details>

**Comment by dparker1005** [comment]
Fixed in v1.0.1 by #59
