### ISSUE TITLE
Fatal Error in `pmprolpv_get_restriction_js` AJAX call

### ISSUE THREAD

**Issue by michaelbourne** [strangerstudios/pmpro-limit-post-views#61]
**Describe the bug**
When viewing a post as a logged out guest, which has no free views given (the LPV field is empty for non-members), the guest is able to see the post, and an AJAX call on the front end to `pmprolpv_get_restriction_js` logs a 500 error in the console.

Possibly a continuation of #57 

`PHP Warning:  Undefined array key 1`
https://github.com/strangerstudios/pmpro-limit-post-views/blob/dev/includes/restriction.php#L72

`PHP Warning:  Undefined array key ""`
`PHP Fatal error:  Uncaught TypeError: Unsupported operand types: string - null`
https://github.com/strangerstudios/pmpro-limit-post-views/blob/dev/includes/restriction.php#L72

**Screenshots**
![image](https://github.com/strangerstudios/pmpro-limit-post-views/assets/22846422/a783efe7-5f6c-48e8-998d-d53abc8055ba)
![image](https://github.com/strangerstudios/pmpro-limit-post-views/assets/22846422/7426bfe9-f3e7-496b-8d51-58bd92ffd72d)

**Expected behavior**
This shouldn't be happening at all. Since no post views are assigned to non-members, I expect the post to load with the default protection message that PMPro offers. 

**Isolating the problem (mark completed items with an [x]):**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
LPV 1.0
PHP 8.1
```
</details>

**Comment by dparker1005** [comment]
This should be resolved in v1.0.1 by #63
